### ISSUE TITLE
Missing data.py

### ISSUE THREAD

**Issue by CedArctic** [FPSG-UIUC/hertzbleed#9]
[hertzbleed/06-circl/README.MD](https://github.com/FPSG-UIUC/hertzbleed/blob/27f45b44c1330a4f3c556082b85d3f1336bd22de/06-circl/README.MD) references a data.py file in the [Attack section](https://github.com/FPSG-UIUC/hertzbleed/blob/27f45b44c1330a4f3c556082b85d3f1336bd22de/06-circl/README.MD#remote-attack-attack). I haven't been able to locate this file. Is it available elsewhere? Thank you.

**Comment by zhdllwyc** [comment]
Added, sorry for late reply. It is ignored by our .gitignore
